Repository Shift3/DevOps-Apprenticeship-Notes, pull requests merged in 2023-02, with the labels that each got.

#5 feat(README): added terraform links
  README.md
Labels: documentation, feature

#26 Nm 6 test phrase
  README.md
Labels: documentation

#9 added a useful command line link
  README.md
Labels: documentation, feature

#18 Nm 6 markdown links
  README.md
Labels: documentation, feature

#41 Update README.md
  README.md
Labels: documentation

#52 Kf 6 add terrafrom doc
  README.md
Labels: documentation

#44 updates
  README.md
Labels: documentation

#63 Fm 6 add coolstuffs links
  README.md
Labels: documentation

#64 feat(README): reorganized all links for better flow
  README.md
Labels: documentation, feature, style

#65 added useful link
  README.md
Labels: documentation

#51 added permission denied info
  README.md
Labels: documentation, feature

#66 added useful document
  README.md
Labels: documentation

#14 add usuful link
  README.md
Labels: documentation
